- name: generate ssh-keys
  import_tasks: keys.yml

- name: Include add user
  import_tasks: access_grant.yml
  when: action == "grant"
 
- name: Include remove user
  import_tasks: access_revoke.yml
  when: action == "revoke"
